swagger:
  auth-url:
  token-url:
  scope:
    - openid
    - profile
api:
  data-store:
    base-url: ''
    username: ''
    password: ''
  auth-jwks-url:
  # signing algorithm: RSA256,
  algorithm: RSA256
  token-verification-class: com.lantanagroup.link.auth.OAuthTokenValidator
  downloader: com.lantanagroup.link.nhsn.MeasureReportDownloader
  sender: com.lantanagroup.link.nhsn.FHIRSender
  patient-id-resolver: com.lantanagroup.link.nhsn.StoredListProvider
  report-aggregator: com.lantanagroup.link.nhsn.ReportAggregator
  data-processor:
    csv: com.lantanagroup.link.thsa.GenericCSVProcessor
    xlsx: com.lantanagroup.link.thsa.GenericXLSXProcessor
  events:
  cors:
    allowed-origins: '*'
    allowed-headers: '*'
    allowed-credentials: false
    allowed-methods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
  document-reference-system: urn:ietf:rfc:3986
  socket-timeout: 30000
  user:
    timezone: UTC
  report-defs:
    max-retry: 5
    retry-wait: 5000
  measure-evaluation-threads: 10

# For scheduled tasks
# CRON format is "<sec> <min> <hour> <day of month> <month> <day of week - 0 index>" and expects UTC
# Examples:
# 3rd day of month: "0 0 0 3 * *"
# every 3 hours: "0 */3 * * * *"
# every 2 minutes: */30 * * * * *"
# 21st day of month at 1:11p PT: "0 11 20 3 * *"
schedule:
#  acquire-census-cron: '0 */3 * * * *'  # every three hours
#  generate-report:
#    - measure-ids:
#        - NHSNGlycemicControlHypoglycemicInitialPopulation
#      reporting-period-method: LastMonth
#      cron: '0 * * * * *'
#      regenerate-if-exists: false
thsa:
  dataMeasureReportId: inventorydata
query:
  require-https: true
  query-class: com.lantanagroup.link.query.uscore.Query
  proxy-address: 23i90u4akdjsf
  allowed-remote:
    - testbadip
    - 0:0:0:0:0:0:0:1
    - 127.0.0.1
    - dev-api.nhsnlink.org
    - test-api.nhsnlink.org
  api-key: 89a83764-9530-4340-9a14-1058b9e84f84c977f983-46e3-4e49-9c3b-869bb2b0f5328ba571b9-e785-4a0b-9fdd-5ff34b8125c47859d241-4ccc-406a-96b6-6fdc918a05e6f3288ebd-927c-4db5
uscore:
  fhir-server-base:
  patient-resource-types:
  other-resource-types:
  parallel-patients: 10
data-governance:
  census-list-retention:
  patient-data-retention:
  report-retention:
